# Generated by Django 2.2.10 on 2021-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date ended'),
        ),
    ]
