# Generated by Django 2.2.10 on 2021-02-11 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20210211_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedsurvey',
            name='date_ended',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 11, 15, 20, 10, 691862, tzinfo=utc), verbose_name='Date ended'),
            preserve_default=False,
        ),
    ]
