# Generated by Django 2.2.10 on 2021-02-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_completedsurvey_date_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='completed_survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.CompletedSurvey'),
            preserve_default=False,
        ),
    ]
